#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/yazi" "$XDG_CONFIG_HOME"/yazi
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.gitconfig" "$HOME"/.gitconfig
ln -sf "$PWD/.tmux" "$HOME"/.tmux
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc

# Install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages
